######################################################################
# Automatically generated by qmake (2.01a) Mon Mar 7 21:15:47 2016
######################################################################

QT+=opengl
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += vis.h
SOURCES += main.cpp vis.cpp
