######################################################################
# Automatically generated by qmake (2.01a) Mon Mar 7 19:55:13 2016
######################################################################

QT+=opengl
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += vis.h
SOURCES += vis.cpp
